#!/bin/bash
log=/var/log/test_masops.log 
cd /root/go/src/github.com/pprisn/test_masops/
export PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin 
exec ./main -ufps C00 &>>$log  & 
exec ./main -ufps R00 &>>$log  & 
exec ./main -ufps R01 &>>$log  & 
exec ./main -ufps R02 &>>$log  & 
exec ./main -ufps R03 &>>$log  & 
exec ./main -ufps R04 &>>$log  & 
exec ./main -ufps R05 &>>$log  & 
exec ./main -ufps R06 &>>$log  & 
exec ./main -ufps R07 &>>$log  & 
exec ./main -ufps R08 &>>$log  & 
exec ./main -ufps R09 &>>$log  & 
exec ./main -ufps R10 &>>$log  & 
exec ./main -ufps R11 &>>$log  & 
exec ./main -ufps R12 &>>$log  & 
exec ./main -ufps R13 &>>$log  & 
exec ./main -ufps R14 &>>$log  & 
exec ./main -ufps R15 &>>$log  & 
exec ./main -ufps R16 &>>$log  & 
exec ./main -ufps R17 &>>$log  & 
exec ./main -ufps R18 &>>$log  & 
exec ./main -ufps R19 &>>$log  & 
exec ./main -ufps R21 &>>$log  & 
exec ./main -ufps R22 &>>$log  & 
exec ./main -ufps R23 &>>$log  & 
exec ./main -ufps R24 &>>$log  & 
exec ./main -ufps R25 &>>$log  & 
exec ./main -ufps R26 &>>$log  & 
exec ./main -ufps R27 &>>$log  & 
exec ./main -ufps R28 &>>$log  & 
exec ./main -ufps R29 &>>$log  & 
exec ./main -ufps R30 &>>$log  & 
exec ./main -ufps R31 &>>$log  & 
exec ./main -ufps R32 &>>$log  & 
exec ./main -ufps R33 &>>$log  & 
exec ./main -ufps R34 &>>$log  & 
exec ./main -ufps R35 &>>$log  & 
exec ./main -ufps R36 &>>$log  & 
exec ./main -ufps R37 &>>$log  & 
exec ./main -ufps R38 &>>$log  & 
exec ./main -ufps R39 &>>$log  & 
exec ./main -ufps R40 &>>$log  & 
exec ./main -ufps R41 &>>$log  & 
exec ./main -ufps R42 &>>$log  & 
exec ./main -ufps R43 &>>$log  & 
exec ./main -ufps R44 &>>$log  & 
exec ./main -ufps R45 &>>$log  & 
exec ./main -ufps R46 &>>$log  & 
exec ./main -ufps R48 &>>$log  & 
exec ./main -ufps R49 &>>$log  & 
exec ./main -ufps R50 &>>$log  & 
exec ./main -ufps R51 &>>$log  & 
exec ./main -ufps R52 &>>$log  & 
exec ./main -ufps R53 &>>$log  & 
exec ./main -ufps R54 &>>$log  & 
exec ./main -ufps R55 &>>$log  & 
exec ./main -ufps R56 &>>$log  & 
exec ./main -ufps R57 &>>$log  & 
exec ./main -ufps R58 &>>$log  & 
exec ./main -ufps R59 &>>$log  & 
exec ./main -ufps R60 &>>$log  & 
exec ./main -ufps R61 &>>$log  & 
exec ./main -ufps R62 &>>$log  & 
exec ./main -ufps R63 &>>$log  & 
exec ./main -ufps R64 &>>$log  & 
exec ./main -ufps R65 &>>$log  & 
exec ./main -ufps R67 &>>$log  & 
exec ./main -ufps R68 &>>$log  & 
exec ./main -ufps R69 &>>$log  & 
exec ./main -ufps R70 &>>$log  & 
exec ./main -ufps R71 &>>$log  & 
exec ./main -ufps R72 &>>$log  & 
exec ./main -ufps R73 &>>$log  & 
exec ./main -ufps R74 &>>$log  & 
exec ./main -ufps R75 &>>$log  & 
exec ./main -ufps R76 &>>$log  & 
exec ./main -ufps R77 &>>$log  & 
exec ./main -ufps R78 &>>$log  & 
exec ./main -ufps R79 &>>$log  & 
exec ./main -ufps R83 &>>$log  & 
exec ./main -ufps R86 &>>$log  & 
exec ./main -ufps R87 &>>$log  & 
exec ./main -ufps R89 &>>$log  & 
exec ./main -ufps R95 &>>$log  & 
exec ./main -ufps R96 &>>$log  & 
